# Table information

metadata: 2004 Time Warner Cable Road Runner 250 | Race | Race
full table:
Driver               | Team                    | Laps | Time_Retired | Grid | Points
------------------------------------------------------------------------------------
Ryan Hunter-Reay     | Herdez Competition      | 250  | 1:59:12.397  | 1    | 34    
Patrick Carpentier   | Forsythe Racing         | 250  | +5.865 secs  | 3    | 27    
Michel Jourdain, Jr. | RuSPORT                 | 250  | +11.349 secs | 9    | 25    
Jimmy Vasser         | PKV Racing              | 249  | + 1 Lap      | 8    | 23    
A. J. Allmendinger   | RuSPORT                 | 249  | + 1 Lap      | 13   | 22    
Bruno Junqueira      | Newman/Haas Racing      | 248  | + 2 Laps     | 10   | 19    
Oriol Servià         | Dale Coyne Racing       | 247  | + 3 Laps     | 11   | 17    
Mario Domínguez      | Herdez Competition      | 246  | + 4 Laps     | 4    | 15    
Rodolfo Lavín        | Forsythe Racing         | 245  | Contact      | 6    | 13    
Mario Haberfeld      | Walker Racing           | 245  | + 5 Laps     | 15   | 11    
Justin Wilson        | Mi-Jack Conquest Racing | 244  | + 6 Laps     | 12   | 10    
Roberto González     | PKV Racing              | 243  | Fire         | 14   | 9     
Alex Tagliani        | Rocketsports Racing     | 243  | + 7 Laps     | 7    | 8     
Nelson Philippe      | Rocketsports Racing     | 240  | + 10 Laps    | 17   | 7     
Alex Sperafico       | Mi-Jack Conquest Racing | 240  | + 10 Laps    | 18   | 6     
Gastón Mazzacane     | Dale Coyne Racing       | 79   | Contact      | 16   | 5     
Paul Tracy           | Forsythe Racing         | 60   | Contact      | 5    | 4     
Sébastien Bourdais   | Newman/Haas Racing      | 50   | Contact      | 2    | 3     

# Statement
The rider on the 2004 Time Warner Cable Road Runner 250 who had 248 laps is Bruno Junqueira.

# Response
```python
import pandas as pd

def expand_statement_pattern(df):
    statement_pattern = "The rider on the {race_name} who had {laps_count} laps is {driver_name}."
    expanded_statement_list = []

    for index, row in df.iterrows():
        race_name = df['Race'].iloc[0]
        laps_count = int(df['Laps'].iloc[0])
        driver_name = df[df['Laps'] == 248]['Driver'].iloc[0]
        expanded_statement = statement_pattern.format(race_name=race_name, laps_count=laps_count, driver_name=driver_name)
        expanded_statement_list.append(expanded_statement)

    return statement_pattern, expanded_statement_list
```

# Exception
Traceback (most recent call last):
  File "/home/go203302/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Race'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/go203302/mtr-lftqa-dataset/expand_statement.py", line 136, in <module>
    statement_pattern, expanded_statement_list = expand_statement_pattern(
  File "<string>", line 8, in expand_statement_pattern
  File "/home/go203302/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/go203302/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Race'

